---
- name: Restart HaProxy
  containers.podman.podman_container:
    name: haproxy
    state: started
    force_restart: true

- name: Restart Prometheus
  containers.podman.podman_container:
    name: prometheus
    state: started
    force_restart: true

- name: Restart Grafana
  containers.podman.podman_container:
    name: grafana
    state: started
    force_restart: true